###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "mautic-theme"
    name: Mautic theme
    type: 
      - mautic-theme
    subtype: mautic
    version: "1.0.0"
    description: "✨📬 Mautic Theme by PIGEONPOSSE"
    homepage: "https://packagist.org/packages/{{composer.name}}"
    logo: "https://raw.githubusercontent.com/pigeonposse/mautic-plugin-extra-tools/main/Assets/img/logo.png"
    repo: "https://github.com/{{composer.name}}"

###############################################################################
